### ISSUE TITLE
There is no button to generate KML file 

### ISSUE THREAD

**Issue by marianairimia99** [sebiboga/gpsmanagement#11]
Environment: LIVE 
            URL: Chrome, https://autobook.space/gps/

Steps to reproduce:
    1. Open URL 
     2. Press button to generate KML file 
Expected results:  
    1. Open URL 
    2. Press button "generate KML file" 
    3. Select file 
     4. Choose export type, example KML
     5. Choose location to save file 
     6. Save KLM file 

Actual results : 
        1. Open URL 
         2. No button to generate KML file

**Comment by bogdangroza** [comment]
There are button to generate KML file
