### ISSUE TITLE
KML Generator button doesn't work

### ISSUE THREAD

**Issue by alingrigore** [sebiboga/gpsmanagement#14]
**ENVIRONMENT**: PRODUCTION
OS: Microsoft Windows 10 Enterprise LTSC 10.0.17763 N/A Build 17763
Browser: Chrome Version 80.0.3987.106 (Official Build) (64-bit)
URL: https://autobook.space/gps/

**STEPS TO REPRODUCE:**
Click "Generate KML  File"

**EXPECTED RESULTS:**
KML file generated 

**ACTUAL RESULTS:**
Nothin happens, KML file isn't generated.

**Comment by sebiboga** [comment]
@bogdangroza please retest

**Comment by bogdangroza** [comment]
KML Generator button are work
