### ISSUE TITLE
When opening the map it would be better to show the points recorded on the map

### ISSUE THREAD

**Issue by bogdangroza** [sebiboga/gpsmanagement#16]
Environment : Live
URL: https://autobook.space/gps/
Browser: Google Chrome

Steps to reproduce:
1. Open URL in browser
2. Click "Culege puncte pe harta"

Expected results: 
Show the points recorded on the map

Actual result:
The map opens without showing the points recorded on the map

**Comment by sebiboga** [comment]
@bogdangroza please retest

**Comment by bogdangroza** [comment]
Retested on live environment the issues is fixed, and closing the bug.
