### ISSUE TITLE
LAT / LNG Entries not ordered in chronological order

### ISSUE THREAD

**Issue by alingrigore** [sebiboga/gpsmanagement#7]
**ENVIRONMENT**: PROD
OS: Windows 10
Browser: Chrome

**STEPS TO REPRODUCE:**
1. Add lat / lng coordinates, click ADD.
2. Observe there is no order in lat / long coordinates

**EXPECTED RESULTS:**
-Chronological ordering of lat / lng entries

**ACTUAL RESULTS:**
- random order of lat / lng entries

**Comment by bogdangroza** [comment]
Retested on live environment 
This issue has been fixed
Closing the bug
